title: Lourah
theme: just-the-docs

url: "https://lourah.com"

color_scheme: "dark"

logo: "/assets/logo.svg"

aux_links:
  "GitHub":
    - "https://github.com/FredOden"

search_enabled: true

sass:
  load_paths:
    - assets
